8 homepage header
nology-tech/niue-ecf pull request #16
Opened 2022-06-29 15:54 UTC by younusk-hub

2022-06-30 14:29 UTC, nologyRob requested changes

2022-06-30 14:29 UTC, nologyRob commented on src/components/WelcomeHeader/WelcomeHeader.jsx
> +    const firstName = userProfile.firstName;
Couldn't this be a one-liner? Seems nicer

2022-06-30 15:20 UTC, Charlie-robin commented on src/components/WelcomeHeader/WelcomeHeader.jsx
> +    const {firstName, lastName, userIcon } = userProfile;
It will be useful to make sure first name & last name are lowercase and capitalised. Can you do this with JS?

2022-07-01 11:22 UTC, nologyRob submitted a review, later dismissed

2022-07-01 11:22 UTC, nologyRob commented on src/components/UserIcon/UserIcon.jsx
> +
Dead space????

2022-07-01 11:22 UTC, nologyRob commented on src/components/WelcomeHeader/WelcomeHeader.jsx
> +
Dead space???!!

2022-07-01 11:22 UTC, nologyRob commented on src/components/WelcomeHeader/WelcomeHeader.jsx
> +
Dead space?

2022-07-01 11:22 UTC, nologyRob commented on src/components/WelcomeHeader/WelcomeHeader.jsx
> +
Dead space

2022-07-01 11:22 UTC, nologyRob commented on src/components/WelcomeHeader/WelcomeHeader.scss
> +
Dead space

2022-07-01 13:24 UTC, aimanwahizam approved these changes

2022-07-01 13:28 UTC, merged