10 setup global styles and variables
nology-tech/niue-ecf pull request #3
Opened 2022-06-27 15:59 UTC by younusk-hub

2022-06-27 16:17 UTC, Charlie-robin requested changes

2022-06-27 16:17 UTC, Charlie-robin commented on package.json
> +<<<<<<< HEAD
Remove the the merge conflict notes. 

```
<<<<<< HEAD
```

2022-06-27 16:17 UTC, Charlie-robin commented on package.json
> +    "sass": "^1.53.0",
`sass` should be a dev dependancy

2022-06-27 16:17 UTC, Charlie-robin commented on src/assets/sass/_variables.scss
> +$primary-color: #B4DDC0;
I am not sure about these names, perhaps something more descriptive?

```scss
$primary-color-green : #B4DDC0;
```
Perhaps we group them similar to how Jake has on the design system page.

![image](https://user-images.githubusercontent.com/55165280/175986672-62a57a61-b6c9-42ca-8b86-b22ea2a5e487.png)

2022-06-27 16:17 UTC, Charlie-robin commented on src/assets/sass/_variables.scss
> +
Let's add some sizes for fonts.

![image](https://user-images.githubusercontent.com/55165280/175987717-24f35760-e71d-4c5e-be68-1f59db16ec05.png)

2022-06-27 16:17 UTC, Charlie-robin commented on src/App.scss
> +.App-logo {
Remove these styles

2022-06-28 14:51 UTC, nologyRob approved these changes

2022-06-28 15:02 UTC, merged